from pyvdp.visadirect.data import VisaDirectTransaction, VisaDirectTransactionBatch


class PullFundsTransaction(VisaDirectTransaction):
    """VisaDirect FundsTransfer PullFunds data object model.

    :param int stan: **Required**. Systems trace audit number.  6 digits integer.
    :param int acquiring_bin: **Required**. Bank identification number (BIN) for VisaDirect acquiring. 6-11 digits
        integer.
    :param int acquirer_country_code: **Required**. `ISO country code <https://developer.visa.com/request_response_codes#isoCodes>`_ for acquiring institution.
    :param float amount: **Required**. Transaction amount nnn.mmm.
    :param str sender_pan: **Required**. Sender PAN (Primary Account Number), 13-19 characters.
    :param str sender_expiration: **Required**. Sender card expiration date, *YYYY-MM*, e.g. 2018-02.
    :param str sender_currency_code: **Required**. Sender currency code, 3 characters `ISO currency code <https://developer.visa.com/request_response_codes#isoCodes>`_.
    :param str business_application_id: **Required**. `Program business application type <https://developer.visa.com/request_response_codes#businessApplicationId>`_.
        2 characters string.
    :param CardAcceptor card_acceptor: **Required**. Instance of :func:`~pyvdp.visadirect.CardAcceptor`.
    :param int mcc: **Conditional**. Merchant category code (MCC). If provided, overrides the one present in
        onboarding data. If missing in onboarding, then this value is required. Max 4 digits integer.
    :param float surcharge: **Optional**. Sender surcharge, as assessed by originator. It must be the same currency and
        format as defined by **sender_currency_code**. Float 12 digits, max 3 fractions.
    :param string cavv: **Optional**. Cardholder Authentication Verification Value (CAVV), generated by ACS.
        Hexbin string, max 40 characters.
    :param str cvv2: **Optional**. Card CVV2 value for **sender_pan**. 3-4 characters string.
    :param float foreign_exchange_fee_transaction: Exchange fee on top of Visa exchange rate. Must be in the same
        currency and format as **amount**. Float 12 digits, max 3 fractions.
    :param MagneticStripeData msd: **Optional**. Instance of :func:`~pyvdp.visadirect.MagneticStripeData`.
    :param PointOfServiceData pos: **Conditional**. Instance of :func:`~pyvdp.visadirect.PointOfServiceData`.
        Required for CardPresent transactions.
    :param PointOfServiceCapability: posc: **Conditional**. Instance of :func:`~pyvdp.visadirect.PointOfServiceCapability`.
        Required for CardPresent transactions.
    :param PinData pin_data: **Optional**. Instance of :func:`~pyvdp.visadirect.PinData`.
    :param str fee_program_indicator: **Optional**. You probably don't need it.
    :param str merchant_pseudo_aba_number: **Optional**. Unique ID for originator when transaction is sent via PPGS.
        9 characters string.
    :param str sharing_group_code: **Optional**. Used by PPG participants to specify network access priority.
        See `Sharing Group Code <https://developer.visa.com/request_response_codes#networkIDAndSharingCode>`_
    :param MerchantVerificationValue mvv: **Optional**. Instance of :func:`~pyvdp.visadirect.MerchantVerificationValue`.
    :param bool multi: **Conditional**. If True, this transaction is a part of batch. See :func:`~pyvdp.visadirect.fundstransfer.MultiPullFundsTransaction`

    **Example:**
        ..  code-block:: json

            {
                "acquirerCountryCode": 840,
                "acquiringBin": 408999,
                "amount": 124.02,
                "businessApplicationId": "AA",
                "cardAcceptor": {
                    "address": {
                        "country": "USA",
                        "county": "San Mateo",
                        "state": "CA",
                        "zipCode": "94404"
                    },
                    "idCode": "ABCD1234ABCD123",
                    "name": "Visa Inc. USA-Foster City",
                    "terminalId": "ABCD1234"
                    },
                "cavv": "0700100038238906000013405823891061668252",
                "foreignExchangeFeeTransaction": "11.99",
                "localTransactionDateTime": "2017-03-17T08:20:42",
                "retrievalReferenceNumber": "330000550000",
                "senderCardExpiryDate": "2015-10",
                "senderCurrencyCode": "USD",
                "senderPrimaryAccountNumber": "4895142232120006",
                "surcharge": "11.99",
                "systemsTraceAuditNumber": "451001"
            }

    """
    ATTR_MAPPINGS = {
        'acquiring_bin': 'acquiringBin',
        'acquirer_country_code': 'acquirerCountryCode',
        'amount': 'amount',
        'sender_pan': 'senderPrimaryAccountNumber',
        'sender_expiration': 'senderCardExpiryDate',
        'sender_currency_code': 'senderCurrencyCode',
        'business_application_id': 'businessApplicationId',
        'card_acceptor': 'cardAcceptor',
        'cavv': 'cavv',
        'surcharge': 'surcharge',
        'cvv2': 'cardCvv2Value',
        'foreign_exchange_fee_transaction': 'foreignExchangeFeeTransaction',
        'mcc': 'merchantCategoryCode',
        'msd': 'magneticStripeData',
        'pos': 'pointOfServiceData',
        'posc': 'pointOfServiceCapability',
        'pin_data': 'pinData',
        'fee_program_indicator': 'feeProgramIndicator',
        'merchant_pseudo_aba_number': 'merchantPseudoAbaNumber',
        'sharing_group_code': 'sharingGroupCode',
        'mvv': 'merchantVerificationValue'
    }

    def __init__(self, **kwargs):
        super(PullFundsTransaction, self).__init__(stan=kwargs['stan'])
        self.__dict__.update((self.ATTR_MAPPINGS[k], v) for k, v in kwargs.items() if k in self.ATTR_MAPPINGS and v)


class MultiPullFundsTransaction(VisaDirectTransactionBatch):
    """VisaDirect FundsTransfer MultiPullFunds data object model.

    It is container object, which incorporate PullFundsTransaction objects under the same acquirer
    credentials.
    
    ..  note::
        
        When instance of PullFundsTransaction incorporated in MultiPullFundsTransaction, attributes `acquirerBin`,
        `acquiringCountryCode` and `businessApplicationId` are migrating from PullFundsTransaction to 
        MultiPullFundsTransaction level.    

    :param int acquiring_bin: **Required**. Bank identification number (BIN) for VisaDirect acquiring. 6-11 digits
        integer.
    :param int acquirer_country_code: **Required**. `ISO country code <https://developer.visa.com/request_response_codes#isoCodes>`_
        for acquiring institution.
    :param str business_application_id: **Required**. `Program business application type <https://developer.visa.com/request_response_codes#businessApplicationId>`_.
        2 characters string.
    :param list request: **Required**. List of :func:`~pyvdp.visadirect.fundstransfer.PullFundsTransaction`
        objects. 

    **Example:**
        ..  code-block:: json

            {
                "acquirerCountryCode": "608",
                "acquiringBin": "408999",
                "businessApplicationId": "AA",
                "localTransactionDateTime": "2017-03-17T09:11:08",
                "merchantCategoryCode": "6012",
                "request": [
                    {
                        "amount": "100.00",
                        "cardAcceptor": {
                            "address": {
                                "country": "USA",
                                "county": "00",
                                "state": "CA",
                                "zipCode": "94454"
                            },
                            "idCode": "5678",
                            "name": "Mr Smith",
                            "terminalId": "1234"
                        },
                        "cavv": "0700020718799100000002980179911000000000",
                        "localTransactionDateTime": "2017-03-17T09:11:08",
                        "retrievalReferenceNumber": "401010101011",
                        "senderCardExpiryDate": "2020-12",
                        "senderCurrencyCode": "USD",
                        "senderPrimaryAccountNumber": "4895140000066666",
                        "systemsTraceAuditNumber": "101011"
                    },
                    {
                        "amount": "100.00",
                        "cardAcceptor": {
                            "address": {
                                "country": "USA",
                                "county": "00",
                                "state": "CA",
                                "zipCode": "94454"
                            },
                            "idCode": "5678",
                            "name": "Mr Smith",
                            "terminalId": "1234"
                        },
                        "cavv": "0700020718799100000002980179911000000000",
                        "localTransactionDateTime": "2017-03-17T09:11:08",
                        "retrievalReferenceNumber": "401010101011",
                        "senderCardExpiryDate": "2020-12",
                        "senderCurrencyCode": "USD",
                        "senderPrimaryAccountNumber": "4895140000066666",
                        "systemsTraceAuditNumber": "101011"
                    }
                ]
            }
    """

    ATTR_MAPPINGS = {
        'acquiring_bin': 'acquiringBin',
        'acquirer_country_code': 'acquirerCountryCode',
        'business_application_id': 'businessApplicationId',
        'request': 'request'
    }

    def __init__(self, **kwargs):
        super(MultiPullFundsTransaction, self).__init__(request=kwargs['request'])
        self.__dict__.update((self.ATTR_MAPPINGS[k], v) for k, v in kwargs.items() if k in self.ATTR_MAPPINGS and v)


class PushFundsTransaction(VisaDirectTransaction):
    """VisaDirect FundsTransfer PushFunds data object model.

    :param int stan: **Required**. Systems trace audit number.  6 digits integer.
    :param int acquiring_bin: **Required**. Bank identification number (BIN) for VisaDirect acquiring.
        6-11 digits integer.
    :param int acquirer_country_code: **Required**. `ISO country code <https://developer.visa.com/request_response_codes#isoCodes>`_ for acquiring institution.
    :param str transaction_currency_code: **Required**. `ISO currency code <https://developer.visa.com/request_response_codes#isoCodes>`_.
        Recommended to use value from :func:`~pyvdp.paai.fundstransferattinq.cardattributes.fundstransferinquiry.send`
        unless prohibited by local law. 3 characters string.
    :param str recipient_pan: **Required**. Recipient primary account number (PAN). 13-19 characters string.
    :param float amount: **Required**. Transaction amount. 12 digits, 3 fractions.
    :param business_application_id: **Required**. `Business application type <https://developer.visa.com/request_response_codes#businessApplicationId>`_
        for VisaNet processing. 2 characters string.
    :param CardAcceptor card_acceptor: **Required**. Instance of :func:`~pyvdp.visadirect.CardAcceptor`.
    :param str sender_reference: **Conditional**. Required, if transaction is money transfer, pre-paid load, credit card
        bill pay and if sender is funding with a non financial instrument (cash). Required if funds disbursement.
        Required if **sender_account_number** is not set. Max 16 characters string.
    :param str sender_account_number: **Conditional**.  If the transaction is a money transfer, pre-paid load, or
        credit card bill pay, and if the sender intends to fund the transaction with a financial instrument (for
        example, debit card), this field is required and must contain the sender's account number. If the transaction
        is a funds disbursement, the field is not required. Max 34 characters string.
    :param str sender_address: **Conditional**. Sender address. Max 35 characters string.
    :param str sender_country_code: **Conditional**. Sender `ISO country code <https://developer.visa.com/request_response_codes#isoCodes>`_.
        Required for cross-border and US domestic money transfers. 2-3 characters string.
    :param str sender_name: **Conditional**. Required for cross-border and US domestic money transfers. Max 30
        characters string.
    :param str sender_city: **Conditional**. Required for cross-border and US domestic money transfers. Max 25
        characters string.
    :param str sender_state_code: **Conditional**. Required if **senderCountryCode** is 124(CAN) or 840(USA). 2 characters
        string.
    :param str recipient_name: **Conditional**. Required for cross-border. Max 30 characters string.
    :param int mcc: **Conditional**. Merchant category code. Overrides the one provided with onboarding data.
        Required if not provided during onboarding. 4 digits integer.
    :param int transaction_identifier: **Conditional**. VisaNet transaction ID. Provide if OCT preceeded by AFT.
        Should be populated with value, returned with AFT. 15 digits integer.
    :param str source_of_funds_code: **Conditional**. Refer to `sourceOfFundsCode <https://developer.visa.com/request_response_codes#sourceOfFundsCode>`_
        codes
    :param str recipient_expiration: **Optional**. Recipient card expiration for **recipient_pan**, YYYY-MM.
    :param str account_type: **Optional**. Used to define account type of the sender PAN. Default '00' (Not applicable).
    :param str fee_program_indicator: **Optional**.
    :param str sender_dob: **Optional**. Sender's date of birth, YYYY-MM-DD.
    :param PointOfServiceData pos: **Conditional**. Instance of :func:`~visa.visadirect.PointOfServiceData`.
        Required for CardPresent transactions.
    :param float surcharge: **Optional**. Sender's surcharge as assessed by originator. Must be in the same format
        and currency as **amount**. 12 digits, 3 fractions float.
    :param str merchant_pseudo_aba_number: **Optional**. Uniquely identifies originator with PPGS. 9 characters string.
    :param str sharing_group_code: **Optional**. Used by PPG participants to specify network priority. 30 characters
        string.
    :param MerchantVerificationValue mvv: **Optional**. Instance of :func:`~pyvdp.visadirect.MerchantVerificationValue`.
    :param bool multi: **Conditional**. If True, this transaction is a part of batch. See :func:`~pyvdp.visadirect.fundstransfer.MultiPushFundsTransaction`

    **Example:**
        ..  code-block:: json

            {
                "acquirerCountryCode": "840",
                "acquiringBin": "408999",
                "amount": "124.05",
                "businessApplicationId": "AA",
                "cardAcceptor": {
                    "address": {
                        "country": "USA",
                        "county": "San Mateo",
                        "state": "CA",
                        "zipCode": "94404"
                    },
                    "idCode": "CA-IDCode-77765",
                    "name": "Visa Inc. USA-Foster City",
                    "terminalId": "TID-9999"
                },
                "localTransactionDateTime": "2017-03-17T09:01:14",
                "merchantCategoryCode": "6012",
                "pointOfServiceData": {
                    "motoECIIndicator": "0",
                    "panEntryMode": "90",
                    "posConditionCode": "00"
                },
                "recipientName": "rohan",
                "recipientPrimaryAccountNumber": "4957030420210462",
                "retrievalReferenceNumber": "412770451018",
                "senderAccountNumber": "4957030420210454",
                "senderAddress": "901 Metro Center Blvd",
                "senderCity": "Foster City",
                "senderCountryCode": "124",
                "senderName": "Mohammed Qasim",
                "senderReference": "",
                "senderStateCode": "CA",
                "sourceOfFundsCode": "05",
                "systemsTraceAuditNumber": "451018",
                "transactionCurrencyCode": "USD",
                "transactionIdentifier": "381228649430015"
            }
    """

    ATTR_MAPPINGS = {
        'amount': 'amount',
        'acquiring_bin': 'acquiringBin',
        'acquirer_country_code': 'acquirerCountryCode',
        'transaction_currency_code': 'transactionCurrencyCode',
        'recipient_pan': 'recipientPrimaryAccountNumber',
        'business_application_id': 'businessApplicationId',
        'card_acceptor': 'cardAcceptor',
        'sender_reference': 'senderReference',
        'sender_account_number': 'senderAccountNumber',
        'sender_address': 'senderAddress',
        'sender_country_code': 'senderCountryCode',
        'sender_name': 'senderName',
        'sender_city': 'senderCity',
        'sender_state_code': 'senderStateCode',
        'recipient_name': 'recipientName',
        'mcc': 'merchantCategoryCode',
        'transaction_identifier': 'transactionIdentifier',
        'source_of_funds_code': 'sourceOfFundsCode',
        'recipient_expiration': 'recipientCardExpiryDate',
        'account_type': 'accountType',
        'fee_program_indicator': 'feeProgramIndicator',
        'sender_dob': 'senderDateOfBirth',
        'pos': 'pointOfServiceData',
        'surcharge': 'surcharge',
        'merchant_pseudo_aba_number': 'merchantPseudoAbaNumber',
        'sharing_group_code': 'sharingGroupCode',
        'mvv': 'merchantVerificationValue'
    }

    def __init__(self, **kwargs):
        super(PushFundsTransaction, self).__init__(stan=kwargs['stan'])
        self.__dict__.update((self.ATTR_MAPPINGS[k], v) for k, v in kwargs.items() if k in self.ATTR_MAPPINGS and v)


class MultiPushFundsTransaction(VisaDirectTransactionBatch):
    """VisaDirect FundsTransfer MultiPushFunds data object model.

    It is container object, which incorporate PushFundsTransaction objects under the same acquirer
    credentials. 
    
    ..  note::
        
        When instance of PushFundsTransaction incorporated in MultiPushFundsTransaction, attributes `acquirerBin`,
        `acquiringCountryCode` and `businessApplicationId` are migrating from PushFundsTransaction to 
        MultiPushFundsTransaction level.

    :param int acquiring_bin: **Required**. Bank identification number (BIN) for VisaDirect acquiring. 6-11 digits
        integer.
    :param int acquirer_country_code: **Required**. `ISO country code <https://developer.visa.com/request_response_codes#isoCodes>`_
        for acquiring institution.
    :param str business_application_id: **Required**. `Program business application type <https://developer.visa.com/request_response_codes#businessApplicationId>`_.
        2 characters string.
    :param list request: **Required**. List of :func:`~pyvdp.visadirect.fundstransfer.PushFundsTransaction`
        objects. 

    **Example:**
        ..  code-block:: json

            {
                "acquirerCountryCode": "840",
                "acquiringBin": "408999",
                "businessApplicationId": "AA",
                "localTransactionDateTime": "2017-03-17T09:12:46",
                "merchantCategoryCode": "6012",
                "request": [
                    {
                        "amount": "100.00",
                        "cardAcceptor": {
                            "address": {
                                "country": "USA",
                                "county": "00",
                                "state": "CA",
                                "zipCode": "94454"
                            },
                            "idCode": "5678",
                            "name": "Mr Smith",
                            "terminalId": "1234"
                        },
                        "feeProgramIndicator": "123",
                        "localTransactionDateTime": "2017-03-17T09:12:46",
                        "recipientName": "Akhila",
                        "recipientPrimaryAccountNumber": "4957030420210454",
                        "retrievalReferenceNumber": "401010101011",
                        "senderAccountNumber": "4005520000011126",
                        "senderAddress": "My Address",
                        "senderCity": "My City",
                        "senderCountryCode": "USA",
                        "senderName": "Mr Name",
                        "senderReference": "",
                        "senderStateCode": "CA",
                        "sourceOfFundsCode": "01",
                        "systemsTraceAuditNumber": "101011",
                        "transactionCurrencyCode": "USD",
                        "transactionIdentifier": "234234234234234"
                    },
                    {
                        "amount": "100.00",
                        "cardAcceptor": {
                            "address": {
                                "country": "USA",
                                "county": "00",
                                "state": "CA",
                                "zipCode": "94454"
                            },
                            "idCode": "5678",
                            "name": "Mr Smith",
                            "terminalId": "1234"
                        },
                        "feeProgramIndicator": "123",
                        "localTransactionDateTime": "2017-03-17T09:12:46",
                        "recipientName": "Akhila",
                        "recipientPrimaryAccountNumber": "4957030420210454",
                        "retrievalReferenceNumber": "401010101012",
                        "senderAccountNumber": "4840920103511221",
                        "senderAddress": "My Address",
                        "senderCity": "My City",
                        "senderCountryCode": "USA",
                        "senderName": "Mr Name",
                        "senderReference": "",
                        "senderStateCode": "CA",
                        "sourceOfFundsCode": "01",
                        "systemsTraceAuditNumber": "101012",
                        "transactionCurrencyCode": "USD",
                        "transactionIdentifier": "234234234234234"
                    }
                ]
            }
    """
    ATTR_MAPPINGS = {
        'acquiring_bin': 'acquiringBin',
        'acquirer_country_code': 'acquirerCountryCode',
        'business_application_id': 'businessApplicationId',
        'request': 'request'
    }

    def __init__(self, **kwargs):
        super(MultiPushFundsTransaction, self).__init__(request=kwargs['request'])
        self.__dict__.update((self.ATTR_MAPPINGS[k], v) for k, v in kwargs.items() if k in self.ATTR_MAPPINGS and v)


class ReverseFundsTransaction(PullFundsTransaction):
    """VisaDirect FundsTransfer ReverseFunds data object model.

    :param int stan: **Required**. Systems trace audit number.  6 digits integer.
    :param int transaction_identifier: **Required**. VisaNet transaction ID. This field must be populated with
        `transactionIdentifier` from initial AFT.
    :param int acquiring_bin: **Required**. Bank identification number (BIN) for VisaDirect acquiring.
        6-11 digits integer.
    :param int acquirer_country_code: **Required**. `ISO country code <https://developer.visa.com/request_response_codes#isoCodes>`_ for acquiring institution.
    :param str sender_pan: **Required**. Primary account number of the sender. 13-19 characters string.
    :param str sender_expiration: **Optional**. Sender card expiration date, YYYY-MM.
    :param str sender_currency_code: **Required**. `ISO currency code <https://developer.visa.com/request_response_codes#isoCodes>`_.
        3 characters string.
    :param float amount: **Required**. Transaction amount. 12 digits, 3 fractions.
    :param float surcharge: **Optional**. Sender's surcharge as assessed by originator. Must be in the same format
        and currency as **amount**. 12 digits, 3 fractions float.
    :param float foreign_exchange_fee_transaction: **Optional**. Foreign exchange markup fee, on top of VisaNet
        exchange rate. 12 digist, 3 fractions float.
    :param OriginalDataElements ode: **Required**. Instance of :func:`~pyvdp.visadirect.OriginalDataElements`.
    :param CardAcceptor card_acceptor: **Required**. Instance of :func:`~pyvdp.visadirect.CardAcceptor`.
    :param PointOfServiceData pos: **Optional**. Instance of :func:`~pyvdp.visadirect.PointOfServiceData`.
    :param PointOfServiceCapability posc: **Optional**. Instance of :func:`~pyvdp.visadirect.PointOfServiceCapability`.
    :param str fee_program_indicator: **Optional**.
    :param str merchant_pseudo_aba_number: **Optional**. Uniquely identifies originator with PPGS. 9 characters string.
    :param str sharing_group_code: **Optional**. Used by PPG participants to specify network priority. 30 characters
        string.
    :param int network_id: **Optional**. Code, that specifies network for transmission. Refer to `Network ID <https://developer.visa.com/request_response_codes#networkIDAndSharingCode>`_.
        2 digits integer.
    :param MerchantVerificationValue mvv: **Optional**. Instance of :func:`~pyvdp.visadirect.MerchantVerificationValue`.
    :param bool multi: **Conditional**. If True, this transaction is a part of batch. See :func:`~pyvdp.visadirect.fundstransfer.MultiPushFundsTransaction`

    **Example:**
        ..  code-block:: json

            {
                "acquirerCountryCode": "608",
                "acquiringBin": "408999",
                "amount": "24.01",
                "cardAcceptor": {
                    "address": {
                        "country": "USA",
                        "county": "San Mateo",
                        "state": "CA",
                        "zipCode": "94404"
                    },
                    "idCode": "VMT200911026070",
                    "name": "Visa Inc. USA-Foster City",
                    "terminalId": "365539"
                },
                "localTransactionDateTime": "2017-03-17T09:02:32",
                "originalDataElements": {
                    "acquiringBin": "408999",
                    "approvalCode": "20304B",
                    "systemsTraceAuditNumber": "897825",
                    "transmissionDateTime": "2017-03-17T09:02:32"
                },
                "pointOfServiceCapability": {
                    "posTerminalEntryCapability": "2",
                    "posTerminalType": "4"
                },
                "pointOfServiceData": {
                    "motoECIIndicator": "0",
                    "panEntryMode": "90",
                    "posConditionCode": "00"
                },
                "retrievalReferenceNumber": "330000550000",
                "senderCardExpiryDate": "2015-10",
                "senderCurrencyCode": "USD",
                "senderPrimaryAccountNumber": "4895100000055127",
                "systemsTraceAuditNumber": "451050",
                "transactionIdentifier": "381228649430011"
            }
    """
    ATTR_MAPPINGS = {
        'transaction_identifier': 'transactionIdentifier',
        'acquiring_bin': 'acquiringBin',
        'acquirer_country_code': 'acquirerCountryCode',
        'sender_pan': 'senderPrimaryAccountNumber',
        'sender_expiration': 'senderCardExpiryDate',
        'sender_currency_code': 'senderCurrencyCode',
        'amount': 'amount',
        'surcharge': 'surcharge',
        'foreign_exchange_fee_transaction': 'foreignExchangeFeeTransaction',
        'ode': 'originalDataElements',
        'card_acceptor': 'cardAcceptor',
        'pos': 'pointOfServiceData',
        'posc': 'pointOfServiceCapability',
        'fee_program_indicator': 'feeProgramIndicator',
        'merchant_pseudo_aba_number': 'merchantPseudoAbaNumber',
        'sharing_group_code': 'sharingGroupCode',
        'network_id': 'networkId',
        'mvv': 'merchantVerificationValue',
    }

    def __init__(self, **kwargs):
        super(ReverseFundsTransaction, self).__init__(**kwargs)
        self.__dict__.update((self.ATTR_MAPPINGS[k], v) for k, v in kwargs.items() if k in self.ATTR_MAPPINGS and v)


class MultiReverseFundsTransaction(MultiPullFundsTransaction):
    """VisaDirect FundsTransfer MultiReverseFunds data object model.

    It is container object, which incorporate ReverseFundsTransaction objects under the same acquirer credentials.

    :param int acquiring_bin: **Required**. Bank identification number (BIN) for VisaDirect acquiring. 6-11 digits
        integer.
    :param int acquirer_country_code: **Required**. `ISO country code <https://developer.visa.com/request_response_codes#isoCodes>`_
        for acquiring institution.
    :param list request: **Required**. List of :func:`~pyvdp.visadirect.fundstransfer.ReverseFundsTransaction`
        objects. 
        
    **Example:**
        ..  code-block:: json

            {
                "acquirerCountryCode": "840",
                "acquiringBin": "408999",
                "localTransactionDateTime": "2017-03-17T09:09:05",
                "request": [
                    {
                        "amount": "100.00",
                        "cardAcceptor": {
                            "address": {
                                "country": "USA",
                                "county": "00",
                                "state": "CA",
                                "zipCode": "94454"
                            },
                            "idCode": "5678",
                            "name": "Mr Smith",
                            "terminalId": "1234"
                        },
                        "localTransactionDateTime": "2017-03-17T09:09:05",
                        "originalDataElements": {
                            "acquiringBin": "408999",
                            "approvalCode": "1ABCDE",
                            "systemsTraceAuditNumber": "228112",
                            "transmissionDateTime": "2017-03-17T09:09:05"
                        },
                        "retrievalReferenceNumber": "401010101011",
                        "senderCardExpiryDate": "2020-12",
                        "senderCurrencyCode": "USD",
                        "senderPrimaryAccountNumber": "4485810000000131",
                        "systemsTraceAuditNumber": "101011",
                        "transactionIdentifier": "101010101010"
                    },
                    {
                        "amount": "100.00",
                        "cardAcceptor": {
                            "address": {
                                "country": "USA",
                                "county": "00",
                                "state": "CA",
                                "zipCode": "94454"
                            },
                            "idCode": "5678",
                            "name": "Mr Smith",
                            "terminalId": "1234"
                        },
                        "localTransactionDateTime": "2017-03-17T09:09:05",
                        "originalDataElements": {
                            "acquiringBin": "408999",
                            "approvalCode": "1ABCDE",
                            "systemsTraceAuditNumber": "228112",
                            "transmissionDateTime": "2017-03-17T09:09:05"
                        },
                        "retrievalReferenceNumber": "401010101011",
                        "senderCardExpiryDate": "2020-12",
                        "senderCurrencyCode": "USD",
                        "senderPrimaryAccountNumber": "4485810000000131",
                        "systemsTraceAuditNumber": "101011",
                        "transactionIdentifier": "101010101010"
                    }
                ]
            }
    """
    ATTR_MAPPINGS = {
        'acquiring_bin': 'acquiringBin',
        'acquirer_country_code': 'acquirerCountryCode',
        'request': 'request'
    }

    def __init__(self, **kwargs):
        super(MultiReverseFundsTransaction, self).__init__(request=kwargs['request'])
        self.__dict__.update((self.ATTR_MAPPINGS[k], v) for k, v in kwargs.items() if k in self.ATTR_MAPPINGS and v)
